# version: 2
# updates:
#   - package-ecosystem: "npm"
#     directory: "/frontend"
#     schedule:
#       interval: "daily"
#     open-pull-requests-limit: 5
#     commit-message:
#       prefix: "deps(npm)"
#     labels:
#       - "dependencies"
#       - "dependabot"

#   - package-ecosystem: "pip"
#     directory: "/backend"
#     schedule:
#       interval: "daily"
#     open-pull-requests-limit: 5
#     commit-message:
#       prefix: "deps(pip)"
#     labels:
#       - "dependencies"
#       - "dependabot"

#   - package-ecosystem: "docker"
#     directory: "/backend"
#     schedule:
#       interval: "weekly"
#     open-pull-requests-limit: 5
#     commit-message:
#       prefix: "deps(docker-backend)"
#     labels:
#       - "dependencies"
#       - "dependabot"

#   - package-ecosystem: "docker"
#     directory: "/frontend"
#     schedule:
#       interval: "weekly"
#     open-pull-requests-limit: 5
#     commit-message:
#       prefix: "deps(docker-frontend)"
#     labels:
#       - "dependencies"
#       - "dependabot"

#   - package-ecosystem: "github-actions"
#     directory: "/"
#     schedule:
#       interval: "weekly"
#     commit-message:
#       prefix: "deps(actions)"
#     labels:
#       - "dependencies"
#       - "labels"
